update workflow

diff --git a/.github/workflows/wc-build-push.yaml b/.github/workflows/wc-build-push.yaml
--- a/.github/workflows/wc-build-push.yaml
+++ b/.github/workflows/wc-build-push.yaml
@@ -46,13 +46,21 @@ jobs:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
 
+      - name: Set ECR destination
+        run: |
+          if [ "${{inputs.destination}}" = "ECR" ]; then
+            echo "ECR_URL=${{ steps.ecr.outputs.registry }}" >> $GITHUB_ENV
+          elif [ "${{inputs.destination}}" = "HUB" ]; then
+            echo "ECR_URL=felixsteph" >> $GITHUB_ENV
+          else
+            echo "Invalid input value provided"
+            exit 1
+          fi
       - name: Build and push
-        env:
-          URL: ${{ steps.ecr.outputs.registry }} if ${{inputs.destination}} == 'ECR' else felixsteph
         uses: docker/build-push-action@v5
         with:
           context: .
           push: true
           dockerfile: ${{inputs.dockerfile}}
-          tags: ${{ env.URL }}/${{inputs.repo}}:${{inputs.image_tag}}
+          tags: ${{ env.ECR_URL }}/${{inputs.repo}}:${{inputs.image_tag}}
         
